on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.goos }}/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: ["linux", "windows", "darwin"]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: amd64
